def preprocess_function(data):
    return [
        data.get('duration', 0),
        data.get('protocol_type', 1),  # already label-encoded
        data.get('service', 1),        # already label-encoded
        data.get('flag', 1),           # already label-encoded
        data.get('src_bytes', 0),
        data.get('dst_bytes', 0),
        data.get('land', 0),
        data.get('wrong_fragment', 0),
        data.get('urgent', 0),
        data.get('hot', 0),
        data.get('num_failed_logins', 0),
        data.get('logged_in', 0),
        data.get('num_compromised', 0),
        data.get('root_shell', 0),
        data.get('su_attempted', 0),
        data.get('num_root', 0),
        data.get('num_file_creations', 0),
        data.get('num_shells', 0),
        data.get('num_access_files', 0),
        data.get('num_outbound_cmds', 0),
        data.get('is_host_login', 0),
        data.get('is_guest_login', 0),
        data.get('count', 0),
        data.get('srv_count', 0),
        data.get('serror_rate', 0.0),
        data.get('srv_serror_rate', 0.0),
        data.get('rerror_rate', 0.0),
        data.get('srv_rerror_rate', 0.0),
        data.get('same_srv_rate', 0.0),
        data.get('diff_srv_rate', 0.0),
        data.get('srv_diff_host_rate', 0.0),
        data.get('dst_host_count', 0),
        data.get('dst_host_srv_count', 0),
        data.get('dst_host_same_srv_rate', 0.0),
        data.get('dst_host_diff_srv_rate', 0.0),
        data.get('dst_host_same_src_port_rate', 0.0),
        data.get('dst_host_srv_diff_host_rate', 0.0),
        data.get('dst_host_serror_rate', 0.0),
        data.get('dst_host_srv_serror_rate', 0.0),
        data.get('dst_host_rerror_rate', 0.0),
        data.get('dst_host_srv_rerror_rate', 0.0)
    ]
